version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yourusername"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: my_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://yourusername:yourpassword@postgres:5432/yourdbname
    ports:
      - "8000:8000"

volumes:
  postgres_data:
