# timeseries-pipeline/config/config.yml

# Metadata
metadata_version: 1.0
metadata_environment: "dev"

# Data Generator - depreciated
# data_generator_enabled: false
# data_generator_random_seed: 1
# data_generator_start_date: "2023-01-01"
# data_generator_end_date: "2023-02-01"
# data_generator_anchor_prices_GME: 150.0
# data_generator_anchor_prices_BYND: 200.0
# data_generator_anchor_prices_BYD: 15.0

# pull internet data or generate synthetic data
source_actual_or_synthetic_data: "actual"  # options: actual, synthetic

# universal data sourcing options
data_start_date: "2023-01-01"
data_end_date: "2023-02-01"
symbols: ["GME", "BYND", "BYD"]

# synthetic-specific options
synthetic_anchor_prices: [150.0, 200.0, 15.0]
synthetic_random_seed: 1

# Data Processor - Missing Values
data_processor_missing_values_enabled: true
data_processor_missing_values_strategy: "drop"  # options: drop, forward_fill

# Data Processor - Stationary
data_processor_stationary_enabled: true
data_processor_stationary_method: "difference"  # options: difference, log

# Data Processor - Stationarity Test
data_processor_stationarity_test_method: "ADF"
data_processor_stationarity_test_p_value_threshold: 0.05

# Data Processor - Scaling
data_processor_scaling_method: "standardize"  # options: standardize, minmax

# ARIMA Model
stats_model_ARIMA_enabled: true
stats_model_ARIMA_fit_p: 2
stats_model_ARIMA_fit_d: 1
stats_model_ARIMA_fit_q: 4
stats_model_ARIMA_predict_steps: 3

# GARCH Model
stats_model_GARCH_enabled: true
stats_model_GARCH_fit_p: 1
stats_model_GARCH_fit_q: 1
stats_model_GARCH_fit_dist: "t"  # options: normal, t
stats_model_GARCH_predict_steps: 3
